// One-off generator for local/reclassification-migration.md's Phase 2 + Phase
// 3: reads every spot's current purpose/vegetation and writes one hand-
// reviewable `UPDATE spots SET purpose = ..., focus = ..., setting = ...`
// statement per row to local/reclassification-data.sql.
//
// Values are only a starting point -- everything flagged REVIEW is a genuine
// judgment call the mapping tables in that doc can't make (see the Field
// mapping section), and every other line is still worth a sanity check
// against the spot on the ground before this file is run for real. This
// script only generates the file; it does not execute anything against the
// database.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { asc } from "drizzle-orm";
import { db } from "./client";
import { spots } from "./schema";

const OUTPUT_PATH = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../local/reclassification-data.sql",
);

// Function, from purpose -- local/reclassification-migration.md's Field
// mapping table. `none` has no target in spotFunctionValues (cultivated/edge/
// built/wild), so it (and anything else unrecognized) falls through to the
// REVIEW path below instead of silently landing somewhere wrong.
const FUNCTION_MAP: Record<string, string> = {
  garden: "cultivated",
  wild_area: "wild",
  monument: "built",
  island: "edge",
};

type FocusSetting = { focus: string | null; setting: string; review: boolean };

// Focus/Setting, from vegetation -- same doc's suggestion table. Genuinely
// ambiguous values (per the doc: vegetable_herb, ornamental, mowed_lawn,
// wetland, vigorous_weeds, and no vegetation at all) are marked for review
// even where a suggested value is filled in.
const FOCUS_SETTING_MAP: Record<string, FocusSetting> = {
  pollinator: { focus: "forbs", setting: "upland", review: false },
  herbaceous_weeds: { focus: "forbs", setting: "upland", review: false },
  vigorous_weeds: { focus: null, setting: "upland", review: true },
  woodland: { focus: "trees", setting: "upland", review: false },
  grassland: { focus: "grasses", setting: "upland", review: false },
  mowed_lawn: { focus: "grasses", setting: "upland", review: true },
  vegetable_herb: { focus: "forbs", setting: "upland", review: true },
  ornamental: { focus: null, setting: "upland", review: true },
  wetland: { focus: null, setting: "wetland", review: true },
  none: { focus: "none", setting: "upland", review: false },
};
const NO_VEGETATION: FocusSetting = { focus: null, setting: "upland", review: true };

// Bloom is net-new (nothing backfills it -- see the migration doc's Bloom
// section), so this is a hand-decided starting point, not derived from any
// old column: May-Sept is a safe default for cultivated-function spots (the
// "gardens" bucket), with two explicit overrides for spots whose real bloom
// window is narrower or later. Overrides apply regardless of function, so
// they still take effect even where Function itself gets hand-corrected.
const BLOOM_MONTHS_CULTIVATED_DEFAULT = [5, 6, 7, 8, 9];
const BLOOM_MONTHS_OVERRIDES: Record<number, number[]> = {
  9: [7],
  10: [7, 8, 9],
};

function sqlLiteral(value: string | null): string {
  return value === null ? "NULL" : `'${value.replace(/'/g, "''")}'`;
}

function sqlComment(value: string | null): string {
  return value === null ? "NULL" : `'${value}'`;
}

function sqlSmallintArray(months: number[]): string {
  return `'{${months.join(",")}}'::smallint[]`;
}

async function main() {
  console.log("Loading spots...");
  const rows = await db
    .select({
      spotId: spots.spotId,
      name: spots.name,
      purpose: spots.purpose,
      vegetation: spots.vegetation,
    })
    .from(spots)
    .orderBy(asc(spots.spotId));
  console.log(`Loaded ${rows.length} spot(s).`);

  const lines: string[] = [
    "-- Generated by `npm run --workspace @placekeeping/db generate-reclassification-data`",
    "-- (packages/db/src/generateReclassificationUpdates.ts) against " +
      `${rows.length} spot(s) on ${new Date().toISOString()}.`,
    "--",
    "-- One UPDATE per spot for Phase 2 (Function swap) + Phase 3 (Focus/",
    "-- Setting) of local/reclassification-migration.md. Values are only a",
    "-- starting-point suggestion from that doc's mapping tables -- every line",
    "-- marked REVIEW needs a human judgment call, and every other line is",
    "-- still worth a sanity check against the spot on the ground. Hand-edit",
    "-- freely; nothing here is authoritative. weed_level is untouched, so it",
    "-- isn't included (see the Overgrowth section of the migration doc).",
    "--",
    "-- Also set setting = 'urban' by hand for street/plaza/shopping-center",
    "-- spots -- the old data can't distinguish those from upland (see Phase 3).",
    "",
  ];

  let reviewCount = 0;
  for (const row of rows) {
    const functionReview = !(row.purpose !== null && row.purpose in FUNCTION_MAP);
    const functionValue = functionReview
      ? row.purpose
      : FUNCTION_MAP[row.purpose as string];

    const focusSetting =
      row.vegetation !== null && row.vegetation in FOCUS_SETTING_MAP
        ? FOCUS_SETTING_MAP[row.vegetation]
        : NO_VEGETATION;

    const needsReview = functionReview || focusSetting.review;
    if (needsReview) reviewCount += 1;

    const bloomMonths =
      BLOOM_MONTHS_OVERRIDES[row.spotId] ??
      (functionValue === "cultivated" ? BLOOM_MONTHS_CULTIVATED_DEFAULT : null);

    lines.push(`-- Spot ${row.spotId}: ${row.name}`);
    lines.push(
      `--   purpose: ${sqlComment(row.purpose)} -> function: ${sqlComment(functionValue)}` +
        (functionReview ? "  -- REVIEW: no direct Function mapping" : ""),
    );
    lines.push(
      `--   vegetation: ${sqlComment(row.vegetation)} -> focus: ${sqlComment(focusSetting.focus)}, setting: ${sqlComment(focusSetting.setting)}` +
        (focusSetting.review ? "  -- REVIEW: ambiguous vegetation reading" : ""),
    );
    if (bloomMonths) {
      lines.push(`--   bloom_months: -> {${bloomMonths.join(",")}}`);
    }

    const setClauses = [
      `purpose = ${sqlLiteral(functionValue)}`,
      `focus = ${sqlLiteral(focusSetting.focus)}`,
      `setting = ${sqlLiteral(focusSetting.setting)}`,
    ];
    if (bloomMonths) {
      setClauses.push(`bloom_months = ${sqlSmallintArray(bloomMonths)}`);
    }
    lines.push(
      `UPDATE spots SET ${setClauses.join(", ")} WHERE spot_id = ${row.spotId};`,
    );
    lines.push("");
  }

  writeFileSync(OUTPUT_PATH, lines.join("\n"), "utf8");
  console.log(`Wrote ${rows.length} statement(s) to ${OUTPUT_PATH}`);
  console.log(`${reviewCount} spot(s) flagged REVIEW.`);
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
