// NY State property classification codes (PROP_CLASS), per the Office of
// Real Property Tax Services manual:
// https://www.tax.ny.gov/research/property/assess/manuals/prclas.htm
export const nyPropertyClassDescriptions: Record<string, string> = {
  // 100 – Agricultural
  "105": "Agricultural vacant land (productive)",
  "110": "Livestock and products",
  "111": "Poultry and poultry products",
  "112": "Dairy products",
  "113": "Cattle, calves, hogs",
  "114": "Sheep and wool",
  "115": "Honey and beeswax",
  "116": "Other livestock (donkeys, goats)",
  "117": "Horse farms",
  "120": "Field crops",
  "129": "Acquired development rights",
  "130": "Truck crops – mucklands",
  "140": "Truck crops – not mucklands",
  "150": "Orchard crops",
  "151": "Apples, pears, peaches, cherries",
  "152": "Vineyards",
  "160": "Other fruits",
  "170": "Nursery and greenhouse",
  "180": "Specialty farms",
  "181": "Fur products",
  "182": "Pheasant",
  "183": "Aquatic (oyster lands, fish)",
  "184": "Livestock (deer, moose, llamas, buffalo)",
  "190": "Fish, game and wildlife preserves",

  // 200 – Residential
  "210": "One family year-round residence",
  "215": "One family year-round residence with accessory apartment",
  "220": "Two family year-round residence",
  "230": "Three family year-round residence",
  "240": "Rural residence with acreage",
  "241": "Primary residential, also used in agricultural production",
  "242": "Recreational use",
  "250": "Estate",
  "260": "Seasonal residences",
  "270": "Manufactured home",
  "271": "Multiple manufactured homes",
  "280": "Residential multi-purpose/multi-structure",
  "281": "Multiple residences",
  "283": "Residence with incidental commercial use",

  // 300 – Vacant Land
  "310": "Residential vacant land",
  "311": "Residential vacant land",
  "312": "Residential land including small improvement",
  "314": "Rural vacant lots of 10 acres or less",
  "315": "Underwater vacant land",
  "320": "Rural vacant land",
  "321": "Abandoned agricultural land",
  "322": "Residential vacant land over 10 acres",
  "323": "Other rural vacant lands",
  "330": "Vacant land located in commercial areas",
  "331": "Commercial vacant land with minor improvements",
  "340": "Vacant land located in industrial areas",
  "341": "Industrial vacant land with minor improvements",
  "350": "Urban renewal or slum clearance",
  "351": "Shell building – residential",
  "352": "Shell building – commercial",
  "380": "Public utility vacant land",

  // 400 – Commercial
  "410": "Living accommodations",
  "411": "Apartments",
  "414": "Hotel",
  "415": "Motel",
  "416": "Manufactured home parks",
  "417": "Camps, cottages, bungalows",
  "418": "Inns, lodges, boarding and rooming houses",
  "420": "Dining establishments",
  "421": "Restaurants",
  "422": "Diners and luncheonettes",
  "423": "Snack bars, drive-ins, ice cream bars",
  "424": "Night clubs",
  "425": "Bar",
  "426": "Fast food franchises",
  "430": "Motor vehicle services",
  "431": "Auto dealers – sales and service",
  "432": "Service and gas stations",
  "433": "Auto body, tire shops",
  "434": "Automatic car wash",
  "435": "Manual car wash",
  "436": "Self-service car wash",
  "437": "Parking garage",
  "438": "Parking lot",
  "439": "Small parking garage",
  "440": "Storage, warehouse and distribution facilities",
  "441": "Fuel storage and distribution facilities",
  "442": "Mini warehouse (self-storage)",
  "443": "Grain and feed elevators",
  "444": "Lumber yards, sawmills",
  "445": "Coal yards, bins",
  "446": "Cold storage facilities",
  "447": "Trucking terminals",
  "448": "Piers, wharves, docks",
  "449": "Other storage, warehouse and distribution",
  "450": "Retail services",
  "451": "Regional shopping centers",
  "452": "Area or neighborhood shopping centers",
  "453": "Large retail outlets",
  "454": "Large retail food stores",
  "455": "Dealerships – sales and service (non-auto)",
  "456": "Medium retail outlet",
  "457": "Small retail outlet",
  "460": "Banks and office buildings",
  "461": "Standard bank – single occupant",
  "462": "Drive-in branch bank",
  "463": "Bank complex with office building",
  "464": "Office building",
  "465": "Professional building",
  "470": "Miscellaneous services",
  "471": "Funeral homes",
  "472": "Dog kennels, veterinary clinics",
  "473": "Greenhouses",
  "474": "Billboards",
  "475": "Junkyards",
  "480": "Multiple use or multi-purpose",
  "481": "Downtown row type (with common wall)",
  "482": "Downtown row type (detached)",
  "483": "Converted residence",
  "484": "One story small structure",
  "485": "One story small structure - multi-occupant",
  "486": "Minimart",

  // 500 – Recreation and Entertainment
  "510": "Entertainment assembly",
  "511": "Legitimate theaters",
  "512": "Motion picture theaters",
  "513": "Drive-in theaters",
  "514": "Auditoriums, exhibition and exposition halls",
  "515": "Radio, television and motion picture studios",
  "520": "Sports assembly",
  "521": "Stadiums, arenas, armories, field houses",
  "522": "Racetracks",
  "530": "Amusement facilities",
  "531": "Fairgrounds",
  "532": "Amusement parks",
  "533": "Game farms",
  "534": "Social organizations",
  "540": "Indoor sports facilities",
  "541": "Bowling centers",
  "542": "Ice or roller skating rinks",
  "543": "YMCA's, YWCA's",
  "544": "Health spas",
  "545": "Indoor swimming pools",
  "546": "Other indoor sports",
  "550": "Outdoor sports activities",
  "551": "Skiing centers",
  "552": "Public golf courses",
  "553": "Private golf country clubs",
  "554": "Outdoor swimming pools",
  "555": "Riding stables",
  "556": "Ice or roller skating rinks (covered)",
  "557": "Other outdoor sports",
  "560": "Improved beaches",
  "570": "Marinas",
  "580": "Camps, camping facilities and resorts",
  "581": "Camps",
  "582": "Camping facilities",
  "583": "Resort complexes",
  "590": "Parks",
  "591": "Playgrounds",
  "592": "Athletic fields",
  "593": "Picnic grounds",

  // 600 – Community Services
  "610": "Education",
  "611": "Libraries",
  "612": "Schools",
  "613": "Colleges and universities",
  "614": "Special schools and institutions",
  "615": "Other educational facilities",
  "620": "Religious",
  "630": "Welfare",
  "631": "Orphanages",
  "632": "Benevolent and moral associations",
  "633": "Homes for the aged",
  "640": "Health",
  "641": "Hospitals",
  "642": "All other health facilities",
  "650": "Government",
  "651": "Highway garage",
  "652": "Office building",
  "653": "Parking lots",
  "660": "Protection",
  "661": "Army, Navy, Air Force, Marine and Coast Guard",
  "662": "Police and fire protection",
  "670": "Correctional",
  "680": "Cultural and recreational",
  "681": "Cultural facilities",
  "682": "Recreational facilities",
  "690": "Miscellaneous",
  "691": "Professional associations",
  "692": "Roads, streets, highways and parkways",
  "693": "Indian reservations",
  "694": "Animal welfare shelters",
  "695": "Cemeteries",

  // 700 – Industrial
  "712": "High-tech – manufacturing and processing",
  "714": "Light industrial – manufacturing and processing",
  "715": "Heavy manufacturing and processing",
  "720": "Mining and quarrying",
  "730": "Wells",
  "731": "Oil – natural flow (for production)",
  "732": "Oil – forced flow (for production)",
  "733": "Gas (for production)",
  "734": "Junk",
  "735": "Water used for oil production",
  "736": "Gas or oil storage wells",
  "740": "Industrial product pipelines",
  "741": "Gas",
  "742": "Water",
  "743": "Brine",
  "744": "Petroleum products",
  "749": "Other",

  // 800 – Public Services
  "820": "Water",
  "821": "Flood control",
  "822": "Water supply",
  "823": "Water treatment facilities",
  "826": "Water transmission – improvements",
  "827": "Water transmission – outside plant",
  "830": "Communication",
  "831": "Telephone",
  "832": "Telegraph",
  "833": "Radio",
  "834": "Television",
  "835": "Community antenna television",
  "836": "Telephone outside plant",
  "837": "Cellular telephone towers",
  "840": "Transportation",
  "841": "Motor vehicle",
  "842": "Ceiling railroad",
  "843": "Non-ceiling railroad",
  "844": "Air",
  "845": "Water",
  "846": "Bridges, tunnels and subways",
  "847": "Pipelines",
  "850": "Waste disposal",
  "851": "Solid wastes",
  "852": "Landfills and dumps",
  "853": "Sewage treatment and water pollution control",
  "854": "Air pollution control",
  "860": "Special franchise property",
  "861": "Electric and gas",
  "862": "Water",
  "866": "Telephone",
  "867": "Miscellaneous",
  "868": "Pipelines",
  "869": "Television",
  "870": "Electric and gas",
  "871": "Electric and gas facilities",
  "872": "Electric substation; electric power generation",
  "873": "Gas measuring and regulation station",
  "874": "Electric power generation facility – hydro",
  "875": "Electric power generation facility – fossil fuel",
  "876": "Electric power generation facility – nuclear",
  "877": "Electric power generation facility – other fuel",
  "878": "Electric power generation facility – solar",
  "879": "Electric power generation facility – wind",
  "880": "Electric and gas transmission and distribution",
  "882": "Electric transmission improvement",
  "883": "Gas transmission improvement",
  "884": "Electric distribution – outside plant property",
  "885": "Gas distribution – outside plant property",

  // 900 – Wild, Forested, Conservation Lands and Public Parks
  "910": "Private wild and forest lands",
  "911": "Forest land under Section 480",
  "912": "Forest land under Section 480-a",
  "920": "Private hunting and fishing clubs",
  "930": "State-owned forest lands",
  "931": "State-owned land (forest preserve) in Adirondack or Catskill Parks",
  "932": "State-owned land other than forest preserve",
  "940": "Reforested land and conservation purposes",
  "941": "State-owned reforested land",
  "942": "County-owned reforested land",
  "950": "Hudson River-Black River Regulating District land",
  "960": "Public parks",
  "961": "State-owned public parks, recreation areas",
  "962": "County-owned public parks and recreation areas",
  "963": "City, town, or village public parks and recreation areas",
  "970": "Other wild or conservation lands",
  "971": "Wetlands",
  "972": "Land under water",
  "980": "Taxable state-owned conservation easements",
  "990": "Other taxable state land assessments",
  "991": "Adirondack Park aggregate additional assessments",
  "992": "Hudson River-Black River Regulating District aggregate",
  "993": "Transition assessments for taxable state-owned land",
  "994": "Transition assessments for exempt state-owned land",
};

// Fallback labels for the hundreds-series header, used when a code isn't
// individually listed above (the manual leaves some numbers in each range
// unassigned/reserved for local use).
const nyPropertyClassSeriesLabels: Record<string, string> = {
  "1": "Agricultural",
  "2": "Residential",
  "3": "Vacant land",
  "4": "Commercial",
  "5": "Recreation and entertainment",
  "6": "Community services",
  "7": "Industrial",
  "8": "Public services",
  "9": "Wild, forested, conservation lands and public parks",
};

// Looks up the human-readable description for a NY PROP_CLASS code, e.g.
// "210" -> "One family year-round residence". Falls back to the hundreds
// series label (e.g. "Residential") for codes not individually listed.
export function describePropertyClass(
  propClass: string | null | undefined,
): string | null {
  if (!propClass) return null;
  const code = propClass.trim();
  if (!code) return null;
  const exact = nyPropertyClassDescriptions[code];
  if (exact) return exact;
  return nyPropertyClassSeriesLabels[code.charAt(0)] ?? null;
}

// Combines the raw code with its description for compact display, e.g.
// "210 – One family year-round residence". Falls back to just the code
// when no description is found.
export function formatPropertyClass(
  propClass: string | null | undefined,
): string | null {
  if (!propClass) return null;
  const description = describePropertyClass(propClass);
  return description ? `${propClass} – ${description}` : propClass;
}
